python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_260k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_260k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_cot_165k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_cot_165k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_nofree_260k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_nofree_260k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_nofree_cot_165k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_nofree_cot_165k.parquet --data-source Video-R1 --num-proc 32

python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_260k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_260k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_cot_165k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_cot_165k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_mcq_260k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_mcq_260k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_mcq_cot_165k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_image_mcq_cot_165k.parquet --data-source Video-R1 --num-proc 32

python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_260k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_260k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_cot_165k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_cot_165k.parquet --data-source Video-R1 --num-proc 32

python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_mcq_260k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_mcq_260k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_mcq_20k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_mcq_20k.parquet --data-source Video-R1 --num-proc 32
python examples/data_preprocess/convert_to_rl_parquet.py /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_mcq_cot_165k.json --media-dir /mnt/amlfs-02/shared/datasets/s3/video_reason/ -o /mnt/amlfs-02/shared/datasets/s3/video_reason/TRAIN/Video-R1/train_video_mcq_cot_165k.parquet --data-source Video-R1 --num-proc 32
